TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: "pretrained_pkl/I3D_8x8_R50.pkl"
#  CHECKPOINT_FILE_PATH: checkpoints_gao/checkpoint_epoch_00196.pyth
DATA:
  NUM_FRAMES: 64
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: "/home/ekim2/Storage/train_data/experiment_setup"
  PATH_LABEL_SEPARATOR: ","
  TARGET_FPS: 25
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0004
  LR_POLICY: cosine
  MAX_EPOCH: 10000
 # MAX_EPOCH: 2
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.0004
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 8
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
TENSORBOARD:
  ENABLE: True
  LOG_DIR: "log/HUMAN"
  CLASS_NAMES_PATH: "dataset/name.json"
  # CLASS_NAMES_PATH: "zhiwen_test/rocog/rocog_id_to_name.json"
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: "dataset/classes.txt"
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized in the confusion matrix.
  HISTOGRAM:
    ENABLE: True
    TOPK: 5   # Top-k most frequently predicted classes for each class in the dataset.
    SUBSET_PATH: "dataset/classes.txt"
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized with histograms.
