TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 28
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: "pretrained_pkl/SLOWFAST_8x8_R50.pkl"
  # CHECKPOINT_FILE_PATH: "checkpoints/checkpoint_epoch_00274.pyth"
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  # TRAIN_JITTER_SCALES: [224, 224]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: "/home/ekim2/Storage/cmu_robocog/Experiment_folder/"
  PATH_LABEL_SEPARATOR: ","
  TARGET_FPS: 30
  MAJORITY_LABELING: False
  RANDOM_FLIP: True
  SPATIAL_SAMPLING: True
  COLOR_JITTER: True
  GAUSSIAN_BLUR: True
  ADJUST_SHARPNESS: True
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  MAX_EPOCH: 1000
 # MAX_EPOCH: 2
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 10
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: "checkpoints/checkpoint_epoch_00660.pyth"
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 4
CLASS_WEIGHT: [0.5701376102,0.8366108881,1.398857647,1.349783619,1.009832814,0.8347774213]
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
TENSORBOARD:
  ENABLE: True
  LOG_DIR: "log/HUMAN"
  CLASS_NAMES_PATH: "/home/ekim2/Storage/cmu_robocog/name.json"
  # CLASS_NAMES_PATH: "zhiwen_test/rocog/rocog_id_to_name.json"
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: "/home/ekim2/Storage/cmu_robocog/classes.txt"
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized in the confusion matrix.
  HISTOGRAM:
    ENABLE: True
    TOPK: 2   # Top-k most frequently predicted classes for each class in the dataset.
    SUBSET_PATH: "/home/ekim2/Storage/cmu_robocog/classes.txt"
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized with histograms.
